[project]
authors = ["Man Yung Ng <ngmanyung222@gmail.com>"]
channels = ["conda-forge"]
description = "This file is for creating an environment to run ethomap by Duncan Mearns. The file is based on Github/DuncanMearns/ethomap/pyproject.toml"
name = "ethomap"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.9,<3.10"
numpy = ">=1.23"
scikit-learn = ">=1.1.0"
scipy = ">=1.9.0"
joblib = ">=1.0.0"
numba = ">=0.56.0"
pip = ">=25.1.1,<26"
